#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase


rm -rf 0/air/cellLevel*
rm -f 0/air/epsilon*
rm -f 0/air/k*
rm -f 0/air/nut*
rm -rf 0/air/pointLevel*
rm -f 0/air/U*

rm -rf ./constant/extendedFeatureEdgeMesh
rm -f ./constant/triSurface/*.eMesh*

# ----------------------------------------------------------------- end-of-file
