#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh > log.blockMesh 2>&1
surfaceFeatures > log.surfaceFeatures 2>&1

echo "Creating mesh"
snappyHexMesh -overwrite > log.snappyHexMesh 2>&1


echo "Running solver"
runApplication `getApplication`
# ----------------------------------------------------------------- end-of-file
